name: CI

on:
  push:
    branches:
      - main
  pull_request: {}
  schedule:
    # Every week at 0.00 UTC.
    - cron: '0 0 * * 0'

# If you trigger a new workflow while the previous one is running,
# this will cancel the previous one.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ##########################################
  # Run tests
  ##########################################
  run_tests:
    name: Run the unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install the dependencies
        run: |
          npm install
      - name: Check linter
        run: |
          make lint-check
      - name: Run health check
        run: |
          make health-check
